### ISSUE TITLE
[Tedious Quest condition mod] Shortcutting the .EXE causes it to crashes

### ISSUE THREAD

**Issue by SGZ-Creations** [kieran-boyle/Mods#54]
![image](https://github.com/user-attachments/assets/475ae8c3-95a3-4d48-b4b9-61162116200e)

**Comment by kieran-boyle** [comment]
The exe cannot be moved as it relies on relative path to find the JSON.  you can right click -> send to desktop if you require a shortcut.

**Comment by kieran-boyle** [comment]
It would be useful to include details, such as which mod this is for, in future issue reports, there is nothing to go off here.

**Comment by SGZ-Creations** [comment]
Tedious Quest condition mod

**Comment by SGZ-Creations** [comment]
> The exe cannot be moved as it relies on relative path to find the JSON. you can right click -> send to desktop if you require a shortcut.

well i was putting it on my start menu as that is where i wanted it. when the crash happened.

**Comment by kieran-boyle** [comment]
Yes, you need to make a **Shortcut** not copy the file.  I have just re-tested and am closing this now.

**Comment by SGZ-Creations** [comment]
> Yes, you need to make a **Shortcut** not copy the file. I have just re-tested and am closing this now.

I didn't copy that won't work i put it on start menu after short cutting that is what crashed it. 
So where did you read copy tell me that?

**Comment by kieran-boyle** [comment]
You are pinning the original to the start menu, not the shortcut, which is what breaks it.  Make a shortcut and pin that.
I read copy because I test things.
You cannot copy the exe as it uses syslinks as I have already stated.
Although weirdly I have no issue with pinning to start straight from where it is installed.  I can only presume it is a system issue.
It is not something I am going to be able to fix as I cannot replicate, nor do I have any will to look further into this.
